inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3

Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'
    - 'lib/darlingtonia/spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/hyrax/basic_metadata.rb'
    - 'lib/darlingtonia/hyrax_record_importer.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/darlingtonia/spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'lib/darlingtonia/hyrax_basic_metadata_mapper.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/support/hyrax/basic_metadata.rb'
    - 'lib/darlingtonia/hyrax_basic_metadata_mapper.rb'
    - lib/darlingtonia/hyrax_record_importer.rb

Naming/AccessorMethodName:
  Exclude:
    - lib/darlingtonia/hyrax_record_importer.rb

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/*_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/darlingtonia/hyrax_basic_metadata_mapper_spec.rb'
    - 'spec/integration/import_hyrax_csv.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/darlingtonia/hyrax_basic_metadata_mapper_spec.rb'
    - 'spec/integration/import_hyrax_csv.rb'
